steps:
- name: gcr.io/cloud-builders/bazel@sha256:4a19236baf0e5d663942c3947497e3f5b5356ae3dd6f97b1fae92897a97a11ad
  id: build
  args: ['run', ':server_image']

- name: gcr.io/cloud-builders/docker
  id: tag
  args: ['tag', 'us-central1-docker.pkg.dev/builder-project/repo1/node_server:server_image', 'us-central1-docker.pkg.dev/$PROJECT_ID/repo1/node_server']
  waitFor: ['build']

- name: 'gcr.io/cloud-builders/docker'
  id: push
  args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/repo1/node_server']
  waitFor: ['tag']

options:
  machineType: 'N1_HIGHCPU_32'


